In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection

In [4]:
data = pd.read_csv('banknotes.txt', sep ='\t')

In [5]:
data.head()

X1     X2     X3    X4    X5     X6  real
0  214.8  131.0  131.1   9.0   9.7  141.0     1
1  214.6  129.7  129.7   8.1   9.5  141.7     1
2  214.8  129.7  129.7   8.7   9.6  142.2     1
3  214.8  129.7  129.6   7.5  10.4  142.0     1
4  215.0  129.6  129.7  10.4   7.7  141.8     1

Отделите 50 случайных наблюдений в тестовую выборку с помощью функции sklearn.cross_validation.train_test_split (зафиксируйте random state = 1). На оставшихся 150 настройте два классификатора поддельности банкнот:

логистическая регрессия по признакам X1,X2,X3;
логистическая регрессия по признакам X4,X5,X6.
Каждым из классификаторов сделайте предсказания меток классов на тестовой выборке. Одинаковы ли доли ошибочных предсказаний двух классификаторов? Проверьте гипотезу, вычислите достигаемый уровень значимости. Введите номер первой значащей цифры (например, если вы получили 5.5×10−8, нужно ввести 8).

In [6]:
dataOne = data.iloc[:, 0:3]

In [7]:
dataOne.head()

X1     X2     X3
0  214.8  131.0  131.1
1  214.6  129.7  129.7
2  214.8  129.7  129.7
3  214.8  129.7  129.6
4  215.0  129.6  129.7

In [8]:
dataTwo = data.iloc[:, 3:6]
dataTwo.head()

X4    X5     X6
0   9.0   9.7  141.0
1   8.1   9.5  141.7
2   8.7   9.6  142.2
3   7.5  10.4  142.0
4  10.4   7.7  141.8

In [9]:
dataTarget = data.iloc[:, -1:]
dataTarget.head()

real
0     1
1     1
2     1
3     1
4     1

In [10]:
dataBegin = data.iloc[:, :-1]
dataBegin.head()

X1     X2     X3    X4    X5     X6
0  214.8  131.0  131.1   9.0   9.7  141.0
1  214.6  129.7  129.7   8.1   9.5  141.7
2  214.8  129.7  129.7   8.7   9.6  142.2
3  214.8  129.7  129.6   7.5  10.4  142.0
4  215.0  129.6  129.7  10.4   7.7  141.8

In [11]:
xTrain, xTest, yTrain, yTest = model_selection.train_test_split(dataBegin,dataTarget, test_size=0.25, random_state=42)

In [12]:
xTrainOne = xTrain.iloc[:, 0:3]
print xTrainOne.head()

xTrainTwo = xTrain.iloc[:, 3:6]
print xTrainTwo.head()

        X1     X2     X3
114  215.1  130.3  130.0
173  214.8  129.6  130.0
5    215.7  130.8  130.5
126  215.0  130.4  130.4
117  214.7  130.4  130.1
       X4    X5     X6
114  10.6  10.8  139.7
173  10.4  11.6  139.2
5     9.0  10.1  141.4
126   9.4  11.6  140.2
117  12.1  10.4  139.9


In [13]:
lgOne = LogisticRegression(solver='liblinear', random_state=1).fit(xTrainOne, yTrain)

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
lgTwo = LogisticRegression(solver='liblinear', random_state=1).fit(xTrainTwo, yTrain)

In [15]:
print len(xTest), len(yTest)

50 50


In [16]:
xTestOne = xTest.iloc[:, 0:3]
print xTestOne.head()

xTestTwo = xTest.iloc[:, 3:6]
print xTestTwo.head()

        X1     X2     X3
95   215.6  129.9  129.9
15   214.5  129.8  129.8
30   215.2  130.1  129.8
158  214.8  130.4  130.6
128  215.1  130.2  130.2
       X4    X5     X6
95    9.0   9.5  141.7
15    9.3   8.5  141.6
30    7.9  10.7  141.8
158  12.5  10.0  139.3
128  10.1  11.3  140.3


In [17]:
lgOne.score(xTestOne, yTest)

0.8

In [18]:
lgTwo.score(xTestTwo, yTest)

0.96

In [19]:
predOne = lgOne.predict(xTestOne)
lgOne.predict(xTestOne)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1], dtype=int64)

In [20]:
yTestnp = yTest.values

In [21]:
predTwo = lgTwo.predict(xTestTwo)
lgTwo.predict(xTestTwo)

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1], dtype=int64)

In [22]:
deffPredTwo = []
for i in np.arange(0,len(predTwo),1):
    if predTwo[i] == yTestnp[i][0]:
        deffPredTwo.append(1)

In [23]:
y= []
for i in yTestnp:
    y.append(i[0])
y = np.array(y)
y

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1], dtype=int64)

In [24]:
deffPredOne = []
for i in np.arange(0,len(predOne),1):
    print predOne[i], y[i]
    if predOne[i] == y[i]:
        print '+ +'
        deffPredOne.append(1)
    else:
        print '- -'
        deffPredOne.append(0)

1 1
+ +
0 1
- -
1 1
+ +
0 0
+ +
0 0
+ +
1 0
- -
0 1
- -
0 0
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
1 0
- -
1 1
+ +
1 1
+ +
0 0
+ +
0 1
- -
0 0
+ +
1 1
+ +
0 1
- -
1 1
+ +
0 1
- -
1 1
+ +
0 0
+ +
0 0
+ +
0 1
- -
1 1
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
0 0
+ +
0 0
+ +
0 0
+ +
0 1
- -
1 1
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
0 1
- -
0 0
+ +
1 1
+ +


In [25]:
deffPredTwo = []
for i in np.arange(0,len(predTwo),1):
    print predTwo[i], y[i]
    if predTwo[i] == y[i]:
        print '+ +'
        deffPredTwo.append(1)
    else:
        print '- -'
        deffPredTwo.append(0)

1 1
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 0
- -
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
1 1
+ +
0 0
+ +
1 1
+ +
1 1
+ +
1 1
+ +
0 1
- -
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
1 1
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
0 0
+ +
0 0
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
0 0
+ +
1 1
+ +
1 1
+ +
0 0
+ +
1 1
+ +


In [26]:
print deffPredOne 
print deffPredTwo

[1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [27]:
deffPredTwoXX = [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [28]:
print deffPredTwoXX

[1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [29]:
def proportions_diff_z_stat_ind(sample1, sample2):
    n1 = len(sample1)
    n2 = len(sample2)
    
    p1 = float(sum(sample1)) / n1
    p2 = float(sum(sample2)) / n2 
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [30]:
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [31]:
from statsmodels.stats.weightstats import ztest
#count = np.array([5, 12])
#nobs = np.array([83, 99])
ztest(deffPredOne , deffPredTwo, alternative='two-sided')

(-2.5144742283748474, 0.01192100149691406)

In [32]:
import scipy

In [33]:
proportions_diff_z_test(proportions_diff_z_stat_ind(deffPredOne , deffPredTwo))

0.0138230238203767

In [40]:
def proportions_diff_z_stat_rel(sample1, sample2, alpha = 0.05):
    sample = list(zip(sample1, sample2))
    n = len(sample1)
    
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    return float(f - g) / np.sqrt(f + g - float((f - g)**2) / n )

In [41]:
proportions_diff_z_test(proportions_diff_z_stat_rel(deffPredOne , deffPredTwoXX))
# Ответ!
#deffPredTwoXX - фиктивная замена deffPredTwo, чтобы сравнить результаты.
# Чем больше значение z_test, тем выше вероятность того, что доли ошибок одинаковы

0.00902343881808032

0.0020282311484520754 - ответ

In [2]:
#В предыдущей задаче посчитайте 95% доверительный интервал для разности долей 
#ошибок двух классификаторов. 
#Чему равна его ближайшая к нулю граница? 
#Округлите до четырёх знаков после десятичной точки.

In [42]:
def proportions_diff_confint_rel(sample1, sample2, alpha = 0.05):
    z = scipy.stats.norm.ppf(1 - alpha / 2.)
    sample = zip(sample1, sample2)
    n = len(sample1)
        
    f = sum([1 if (x[0] == 1 and x[1] == 0) else 0 for x in sample])
    g = sum([1 if (x[0] == 0 and x[1] == 1) else 0 for x in sample])
    
    left_boundary = float(f - g) / n  - z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    right_boundary = float(f - g) / n  + z * np.sqrt(float((f + g)) / n**2 - float((f - g)**2) / n**3)
    return (left_boundary, right_boundary)

In [43]:
proportions_diff_confint_rel(deffPredOne , deffPredTwoXX)

(-0.21007308715318906, -0.02992691284681094)