In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[2,4,6],[3,6,9]])
print('matrix\n', a)

matrix
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [5]:
c = np.eye(5,4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [8]:
c = np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
c = np.zeros((4,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
v = np.arange(1,2,0.1)
print(v)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [38]:
d = len(v)/2
vv = v.reshape((int(d),2))
print(vv)

[[1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]]


In [49]:
print(vv[2,1])
print(vv[2, :], '\t',vv[:,1])

1.5000000000000004
[1.4 1.5] 	 [1.1 1.3 1.5 1.7 1.9]


In [56]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a, '\t', a.shape, '\n','\n', b, '\t', b.shape)
print('\n','\n',b.T, '\t', b.shape)

[1 2 3] 	 (3,) 
 
 [[1]
 [2]
 [3]] 	 (3, 1)

 
 [[1 2 3]] 	 (3, 1)


In [98]:
a = np.array([[1,2,1],[4,5,6],[3,7,9]])
b = np.linalg.inv(a)
c = np.dot(a,b)
print(a, '\n', '\n', b, '\n', '\n', c.round())


[[1 2 1]
 [4 5 6]
 [3 7 9]] 
 
 [[-0.15  0.55 -0.35]
 [ 0.9  -0.3   0.1 ]
 [-0.65  0.05  0.15]] 
 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]


In [99]:
a = np.array([[1,1,2],[0,1,2]])
b = np.linalg.matrix_rank(a)
print(b)

2
