In [2]:
import numpy as np

In [4]:
a = np.array(range(1,6), dtype=float)
print(a)

[1. 2. 3. 4. 5.]


In [5]:
a.dtype

dtype('float64')

In [8]:
d = np.arange(start=10.5, stop=21, step=2, dtype=float)
print(d)

[10.5 12.5 14.5 16.5 18.5 20.5]


In [9]:
d.ndim

1

In [10]:
d.shape

(6,)

In [11]:
a = np.array([1,2,3])
b = np.array([6,5,4])
k = 2

print (a,b,k)

[1 2 3] [6 5 4] 2


In [12]:
print ('+ ', a+b, ' - ', a-b, ' * ', a*b, ' k*a ', k*a)

+  [7 7 7]  -  [-5 -3 -1]  *  [ 6 10 12]  k*a  [2 4 6]


In [14]:
from numpy.linalg import norm

In [15]:
print(norm(a, ord=1))

6.0


In [17]:
print(norm(a, ord=2))

3.7416573867739413


In [18]:
print(norm(a-b, ord=1), ' ', norm(b-a, ord=1))

9.0   9.0


In [19]:
print(norm(a-b, ord=2), ' ', norm(b-a, ord=2))

5.916079783099616   5.916079783099616


In [21]:
a = a.reshape(1,3)
b = b.reshape(1,3)
print(a,'\n',b)

[[1 2 3]] 
 [[6 5 4]]


In [28]:
from scipy.spatial.distance import cdist

In [29]:
print(cdist(a,b,metric='cityblock'))

[[9.]]


In [38]:
d = np.array([3,0,8,9,-10])
print(d)
print(d.shape)

[  3   0   8   9 -10]
(5,)


In [39]:
dd = d[np.newaxis, :]
print(dd)
print(dd.shape)

[[  3   0   8   9 -10]]
(1, 5)


In [40]:
ddd = d[:, np.newaxis]
print(ddd)
print(ddd.shape)

[[  3]
 [  0]
 [  8]
 [  9]
 [-10]]
(5, 1)


In [73]:
a = np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8],[8,9,10,11]])
b = np.array([[3,2,1,0],[0,-1,-2,-3],[4,3,2,1],[0,1,2,3]])
#print(a)
#print(cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean'))
print(cdist(a,b,metric='euclidean', p=2))

[[ 4.89897949  9.16515139  4.47213595  2.        ]
 [ 6.         10.95445115  4.89897949  4.        ]
 [10.95445115 16.61324773  9.16515139 10.        ]
 [16.61324773 22.44994432 14.69693846 16.        ]]


In [79]:
import numpy as np

matrix = np.array(
    [
        [1, 0],
        [1, 1],
    ])

lambdas, V =  np.linalg.eig(matrix.T)
# The linearly dependent row vectors 
print (matrix[lambdas == 0,:])

[]


In [92]:
a = np.array([1,2,3], dtype=float)
b = np.array([-3,1,1], dtype=float)
#aa = a[np.newaxis, :]
print(np.dot(a,b))

2.0


In [95]:
f = np.arange(1, 2, 0.3, dtype=float)
print(f)

[1.  1.3 1.6 1.9]


In [100]:
a = np.array([8, 10, -1, 0, 0])
#print(a.reshape((5,1)))
print(a[:, np.newaxis])

[[ 8]
 [10]
 [-1]
 [ 0]
 [ 0]]
