Посмотрим на данные General Social Survey 2014 года и проанализируем, как связаны ответы на вопросы "Счастливы ли вы?" и "Довольны ли вы вашим финансовым положением?"




In [1]:
#                       не доволен     более или менее     доволен
#не очень счастлив      197             111                33
#достаточно счастлив    382             685                331
#очень счастлив         110             342                333

Чему равно значение статистики хи-квадрат для этой таблицы сопряжённости? Округлите ответ до четырёх знаков после десятичной точки.

In [78]:
import numpy as np
import pandas as pd
import math
from pandas import DataFrame

from scipy.stats import chi2_contingency

In [37]:
table = [ [ 197, 382,110 ], 
         [ 111, 685, 342 ], 
         [33, 331, 333] ]

chi2, prob, df, expected = chi2_contingency(table)

In [38]:
chi2

293.68311039689746

In [32]:
prob

2.4964299580093467e-62

In [33]:
expected

array([[ 93.08597464, 381.6251981 , 214.28882726],
       [153.74722662, 630.318542  , 353.93423138],
       [ 94.16679873, 386.0562599 , 216.77694136]])

In [34]:
chi2_contingency(table)

(293.68311039689746,
 2.4964299580093467e-62,
 4L,
 array([[ 93.08597464, 381.6251981 , 214.28882726],
        [153.74722662, 630.318542  , 353.93423138],
        [ 94.16679873, 386.0562599 , 216.77694136]]))

На данных из предыдущего вопроса посчитайте значение достигаемого уровня значимости. Введите номер первой значащей цифры (например, если вы получили 5.5×10−8, нужно ввести 8).

In [36]:
#62

Чему в предыдущей задаче равно значение коэффициента V Крамера для рассматриваемых признаков? Округлите ответ до четырёх знаков после десятичной точки.

In [41]:
table

[[197, 382, 110], [111, 685, 342], [33, 331, 333]]

In [50]:
col1 = [table[0][0], table[1][0], table[2][0]]  
col1

[197, 111, 33]

In [51]:
col2 = [table[0][1], table[1][1], table[2][1]]  
col2

[382, 685, 331]

In [52]:
col3 = [table[0][2], table[1][2], table[2][2]]  
col3

[110, 342, 333]

In [70]:
pdcol1 = pd.DataFrame(col1)
pdcol1[0]

0    197
1    111
2     33
Name: 0, dtype: int64

In [66]:
pdcol2 = pd.DataFrame(col2)
pdcol2

0
0  382
1  685
2  331

In [65]:
pdcol3 = pd.DataFrame(col3)
pdcol3

0
0  110
1  342
2  333

In [83]:
pdTable = pd.DataFrame(table)

In [86]:
pdTable.pivot_table

<bound method DataFrame.pivot_table of      0    1    2
0  197  382  110
1  111  685  342
2   33  331  333>

In [87]:
pdTable

0    1    2
0  197  382  110
1  111  685  342
2   33  331  333

In [88]:
table

[[197, 382, 110], [111, 685, 342], [33, 331, 333]]

In [75]:
def cramers_corrected_stat(confusion_matrix):
    """ calculate Cramers V statistic for categorial-categorial association.
        uses correction from Bergsma and Wicher, 
        Journal of the Korean Statistical Society 42 (2013): 323-328
    """
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum()
    phi2 = chi2/n
    r,k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))    
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    return np.sqrt(phi2corr / min( (kcorr-1), (rcorr-1)))

In [94]:
table

[[197, 382, 110], [111, 685, 342], [33, 331, 333]]

In [95]:
np.transpose(table)

array([[197, 111,  33],
       [382, 685, 331],
       [110, 342, 333]])

In [97]:
cramers_corrected_stat(np.transpose(table))

0.2412013934500338