In [2]:
import numpy as np

In [5]:
x= [2,3,4,6]
y= np.array(x)

print (x)
print (y)

[2, 3, 4, 6]
[2 3 4 6]


In [8]:
print (x[0:4])
print (y[0:4])

[2, 3, 4, 6]
[2 3 4 6]


In [16]:
print (y[[0,2]])

[2 4]


In [54]:
print (y[y>3])

[4 6]


In [21]:
print (x*10)
print (y*10)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]
[20 30 40 60]


In [28]:
matr = [[1,2,3],[3,2,1]]
np_array = np.array(matr)
print (matr)
print (np_array)
#print (matr[1,2])
print (np_array[1,2])

[[1, 2, 3], [3, 2, 1]]
[[1 2 3]
 [3 2 1]]
1


In [30]:
print(np.arange(5, 25, 5))

[ 5 10 15 20]


In [34]:
%timeit np.arange(0, 10000)

5.92 µs ± 70.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# SciPy

In [36]:
from scipy import optimize

In [50]:
def t(x):
    return (x[0]-3.2)**2 + (x[1]-0.1)**2 + 3

print (t([3.19999896 ,0.10000026]))

3.0000000000011493


In [51]:
x_min = optimize.minimize(t,[5.0,5.0])
print(x_min)

      fun: 3.0000000000011435
 hess_inv: array([[ 0.94055055, -0.16183475],
       [-0.16183475,  0.55944947]])
      jac: array([-2.05636024e-06,  5.36441803e-07])
  message: 'Optimization terminated successfully.'
     nfev: 16
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([3.19999896, 0.10000026])


In [53]:
print(x_min.
      x)


[3.19999896 0.10000026]


In [99]:
z = [[1,2,3],[3,2,1]]
zz = np.ndarray([2,3])
print(zz.shape)
print(zz[0,1])

(2, 3)
0.0


In [221]:
r = range(1,11)
for i in r:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [225]:
x = range(0,51)
h=0
i=0
for i in x:
    h=h+i
    #print(i)

print(h)
print(len(x))
print(h / len(x))

1275
51
25.0
